# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Suwayomi.Tachidesk-Sorayomi
PackageVersion: 0.5.18
PackageLocale: en-US
Publisher: Suwayomi
PublisherUrl: https://github.com/Suwayomi
PublisherSupportUrl: https://github.com/Suwayomi/Tachidesk-Sorayomi/issues
PackageName: Tachidesk Sorayomi
PackageUrl: https://github.com/Suwayomi/Tachidesk-Sorayomi
License: MPL-2.0
LicenseUrl: https://github.com/Suwayomi/Tachidesk-Sorayomi/blob/main/LICENSE
ShortDescription: A free and open source manga reader based on Flutter to read manga from a Tachidesk-Server instance.
Moniker: tachidesk-sorayomi
Tags:
- cross-platform
- foss
- manga-reader
- open-source
- tachiyomi
ReleaseNotes: |-
  What's Changed
  - Fixed Downloads Screen for Auth Enabled Servers
  - Fixed Download Screen performance issue on 1000+ downloads
  - Fixed Some languages missing in Source screen
  - Added new Shortcuts to navigate through Chapter
  - Space - scroll to Next page
  - Shift + Space - scroll to Previous page
  Commits
  - Web sockets io fix by @DattatreyaReddy in #245
  - Translations update from Hosted Weblate by @weblate in #244
  - Downloads-performance by @DattatreyaReddy in #251
  - Translations update from Hosted Weblate by @weblate in #249
ReleaseNotesUrl: https://github.com/Suwayomi/Tachidesk-Sorayomi/releases/tag/0.5.18
ManifestType: defaultLocale
ManifestVersion: 1.5.0
