# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Suwayomi.Tachidesk-Sorayomi
PackageVersion: 0.5.22
InstallerLocale: en-US
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{BD8555A8-8235-490D-98CA-9F9097C71596}'
ReleaseDate: 2024-01-16
AppsAndFeaturesEntries:
- UpgradeCode: '{73ED8344-B8C4-4AEE-A7F5-869829B986A1}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Suwayomi/Tachidesk-Sorayomi/releases/download/0.5.22/tachidesk-sorayomi-0.5.22-windows-x64.msi
  InstallerSha256: BF63D94F2E028656C6F4595677C5DFCA501B70F06B47D445D815CB5F168F5D08
ManifestType: installer
ManifestVersion: 1.5.0
